### ISSUE TITLE
how to login with ldap

### ISSUE THREAD

**Issue by chaoweiWang** [JavaChinna/spring-boot-rest-ldap-auth#1]
![image](https://user-images.githubusercontent.com/41568467/84336480-e9f2c880-abc9-11ea-8487-265731ba07ef.png)

i use profile with 'ldapauth', but the authorizations is alway Bearer  (apiKey) and Basic authorization,when i type username and password ,there is no request send.

**Comment by JavaChinna** [comment]
You should enter the credentials in Basic Authorization. After that you should be able to execute service. Please refer the screenshots below.
![Ldap_auth](https://user-images.githubusercontent.com/23244086/85014580-28692400-b184-11ea-9ff5-ac5b149e2f58.JPG)

**Request & Response**

![Request_response](https://user-images.githubusercontent.com/23244086/85014642-433b9880-b184-11ea-8c52-4521d0b229cb.JPG)

Make sure that 

1. You are able to connect to the LDAP server 
2. LDAP user credentials are correct
3. You have a user with the same user name in the 'user' database table

For more information, you can refer this [article](https://www.javachinna.com/2020/06/01/secure-spring-boot-rest-api-using-ldap-authentication-and-authorization-with-database/)

Please let me know if I can close this issue

**Comment by chaoweiWang** [comment]
why use profile with 'ldapauth' need a user with the same user name in the 'user' database table? why not query this user from ldap directly? i am not understand.

**Comment by JavaChinna** [comment]
LDAP server provides authentication only not the user authorities. For role based authorization, we need to fetch the roles of the logged-in user from the database. If the user is having "admin" role, then he is allowed to perform update and delete operations. Other users are allowed to perform POST and GET operations only. 

I've explained all this in this [article](https://www.javachinna.com/2020/06/01/secure-spring-boot-rest-api-using-ldap-authentication-and-authorization-with-database/)

If you dont want authorization, then 

- Remove the `LdapUserAuthoritiesPopulator` class and its  configuration from the `LdapAuthSecurityConfig` class.  Change the `hasRole` and `hasAnyRole` methods to `authenticated` method to allow all the authenticated users to perform all the operations. 

- Remove @PreAuthorize("hasRole('ROLE_ADMIN')") from `ProductController`

Hope it clarifies your queries.
